### ISSUE TITLE
As a user I want to have the possibility to change the reporting scale

### ISSUE THREAD

**Issue by daviatorstorm** [daviatorstorm/FullCalendarWR#16]
As a user I want to have the possibility to change the reporting scale view (day; week and month)
Click on "Day" button - shows day selected by user;
Click on "Week" button - shows week, which contains day selected by user;
Click on "Month" button - shows month, which contains day selected by user, starting from 1st day of the month;
Feature should work like Google Calendar
![image](https://cloud.githubusercontent.com/assets/4057612/5561241/634f9048-8dd3-11e4-8580-73785bbc4e85.png)
![image](https://cloud.githubusercontent.com/assets/4057612/5561242/6887dcfa-8dd3-11e4-9980-3bd08bcbf36a.png)
![image](https://cloud.githubusercontent.com/assets/4057612/5561243/6d343c80-8dd3-11e4-9627-dca3381b2087.png)

**Comment by ViktorBidnyna** [comment]
Added css styles which user want )
