### ISSUE TITLE
As a user I want to have Repoting in Calendar view

### ISSUE THREAD

**Issue by daviatorstorm** [daviatorstorm/FullCalendarWR#17]
As a user I want to have Repoting in Calendar view
Reported hrs should be in Calendar view (similar to Google calendar)
![image](https://cloud.githubusercontent.com/assets/4057612/5561246/80680890-8dd3-11e4-9daf-7698692d01ec.png)
![image](https://cloud.githubusercontent.com/assets/4057612/5561247/865127d2-8dd3-11e4-959e-d241c43f66f9.png)

**Comment by AnnaKusa** [comment]
I did it !!

**Comment by VasylVovkovych** [comment]
Made Monday as first day of the week in FullCalendar so now it looks more like Calendar view on the pictures above.
