### ISSUE TITLE
As a user I want to see notification when time slot is busy and have hrs autocorrected

### ISSUE THREAD

**Issue by daviatorstorm** [daviatorstorm/FullCalendarWR#18]
When user clicks on free slot on calendar to Add new task - but into "From" and "To" fields enters busy time interval - there should be notification "This slot is busy" at the top of the "Add new task" page and time should be corrected automatically (should be changed to time which corresponds with selected slot)

**Comment by VasylVovkovych** [comment]
ede270066a862ec50501c872ed2a2b2026dc4814
