### ISSUE TITLE
Create little calendar

### ISSUE THREAD

**Issue by daviatorstorm** [daviatorstorm/FullCalendarWR#22]
Create calendar like shows at the image below
![image](https://cloud.githubusercontent.com/assets/4057612/5574288/a4115124-8fc3-11e4-93f8-620d6132097b.png)
with these parameters shows below
![image](https://cloud.githubusercontent.com/assets/4057612/5574299/05a5fc50-8fc4-11e4-8721-91fc2c5e7184.png)
For more simplisity can be used calendar from teammates + some styles.
Core issue: https://github.com/daviatorstorm/FullCalendarWR/issues/13

**Comment by VasylVovkovych** [comment]
done&done
