### ISSUE TITLE
right menu bug

### ISSUE THREAD

**Issue by AnnaSobchuk** [daviatorstorm/FullCalendarWR#26]
it should be:
![bug1](https://cloud.githubusercontent.com/assets/9572209/5720819/1662d76a-9b32-11e4-96e0-db3dcabf35c9.JPG)
it is: 
![after](https://cloud.githubusercontent.com/assets/9572209/5720823/27bc4866-9b32-11e4-85d4-955a1d19b8ad.JPG)

**Comment by AnnaSobchuk** [comment]
working menu 
\\fstrain\Exchange\129.Net\Sobchuk\career 2

**Comment by VasylVovkovych** [comment]
fuck off, you fucking bug!
