### ISSUE TITLE
Insert report to db

### ISSUE THREAD

**Issue by daviatorstorm** [daviatorstorm/FullCalendarWR#56]
Function
Name "Insert Report To DB"
Arguments { object }
object - object with "Report" type
Description: Function that pastes Report type object to DB using ajax.

**Comment by daviatorstorm** [comment]
Sorry but this is dublicate of https://github.com/daviatorstorm/FullCalendarWR/issues/36

**Comment by ViktorBidnyna** [comment]
Done
