### ISSUE TITLE
copy and past events

### ISSUE THREAD

**Issue by AnnaKusa** [daviatorstorm/FullCalendarWR#62]
зробити можливість копіювати і вставляти інформацію про івенти в модальне вікно

**Comment by daviatorstorm** [comment]
шо буде функція приймати?

**Comment by AnnaKusa** [comment]
id івента. і копіювати основну інформацію, без годин напевне.

**Comment by daviatorstorm** [comment]
Обєкт івент не має повної інформації для вставляння її у всі поля модального вікна.

**Comment by daviatorstorm** [comment]
https://github.com/daviatorstorm/FullCalendarWR/commit/90e5508b18615bf5b1d4758b1e5d650ca2c2e5b9
