### ISSUE TITLE
Edite Event on fullcalendar and db

### ISSUE THREAD

**Issue by AnnaKusa** [daviatorstorm/FullCalendarWR#67]
при кліку на івент повинно появлятися модальне вікно з шапкою Edit report, всі поля повинні бути заповненні відповідно до індексу даного івенту. при натисканні кнопки сейв внесені зміни повинні апдейтатися в бд

**Comment by daviatorstorm** [comment]
Звідки мені витягувати витягувати інформацію для полів модального вікна

**Comment by daviatorstorm** [comment]
977600b0b153886593e56020c1c578cc28d092d8
