### ISSUE TITLE
weird time of saving

### ISSUE THREAD

**Issue by AnnaSobchuk** [daviatorstorm/FullCalendarWR#69]
таски зберігаються не на той день і час який вибирається

**Comment by ViktorBidnyna** [comment]
Closed

**Comment by AnnaSobchuk** [comment]
все ще при додаванні репорта додає 2 год

**Comment by ViktorBidnyna** [comment]
Мені здається юра пофіксив цей баг

**Comment by ViktorBidnyna** [comment]
і зараз нормально відображає тому я закриваю цей баг
