### ISSUE TITLE
add task and activiti on modal view when edit

### ISSUE THREAD

**Issue by AnnaKusa** [daviatorstorm/FullCalendarWR#76]
![default](https://cloud.githubusercontent.com/assets/2743538/5966487/7deb68ec-a80d-11e4-8018-a4e2c32cf5fe.png)

**Comment by AnnaKusa** [comment]
Ну народ... то теж має виводитися

**Comment by daviatorstorm** [comment]
https://github.com/daviatorstorm/FullCalendarWR/commit/fd666dec36573d08675fbc62e3ecde4a37d73c14

**Comment by SlotskyiSergii** [comment]
![bugpic](https://cloud.githubusercontent.com/assets/9626298/5978034/5f6c94b6-a8a5-11e4-8cb5-7e47f1c47947.png)
Bug not fixed

**Comment by daviatorstorm** [comment]
9db754ae40b70a8f09765fe93b3e19d569e5d425
