### ISSUE TITLE
Clean "new report" form

### ISSUE THREAD

**Issue by AnnaKusa** [daviatorstorm/FullCalendarWR#77]
![default](https://cloud.githubusercontent.com/assets/2743538/5966680/31eac8a0-a80f-11e4-8cb1-4801fed026c2.png)

**Comment by AnnaKusa** [comment]
Я думаю, там перед викликом того вікна просто треба ті поля занулити і все буде гуд :)

**Comment by daviatorstorm** [comment]
Є готова функція для того

**Comment by daviatorstorm** [comment]
Є готова функція для того

**Comment by daviatorstorm** [comment]
I think that it must be a function that will just clean all values from modal window accept selectProjects and must be universal to be able to use everywhere.

**Comment by ViktorBidnyna** [comment]
Done
